name: "Index search on a pantheon target"
description: "Runs search indexing if testing requires it."
inputs:
  pantheon-site-name:
    description: 'The site name, such as bps-district'
    required: true
  multidev-name:
    description: "The name of the environment: dev, edge, pr-[x]"
    required: true
  machine-token:
    description: "The machine token needed to authorize terminus"
    required: true

runs:
  using: composite
  steps:
    - name: 'Run search indexing if needed.'
      id: search-indexing
      env:
        PANTHEON_SITE_NAME: ${{ inputs.pantheon-site-name }}
        MULTIDEV_NAME: ${{ inputs.multidev-name }}
        MACHINE_TOKEN: ${{ inputs.machine-token }}
      shell: bash
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        terminus auth:login --machine-token="${{ env.MACHINE_TOKEN }}"
        drainpipe_exec "terminus remote:drush ${{ env.PANTHEON_SITE_NAME }}.${{ env.MULTIDEV_NAME }} -- search-api:reset-tracker"
        drainpipe_exec "terminus remote:drush ${{ env.PANTHEON_SITE_NAME }}.${{ env.MULTIDEV_NAME }} -- search-api:index"
